# DataSource
spring:
  datasource:
    url: jdbc:h2:mem:dispatch
    username: sa
    password:
    generate-unique-name: false
    diverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
# Mybatis
mybatis:
  mapper-locations:
    mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true